# Github defaults:
# safe: true
# lsi: false
# pygments: true

# Settings
baseurl: /apuntes

markdown: kramdown
kramdown:
  parse_span_html: false

permalink: /:title
paginate: 4
paginate_path: p/:num

#nav_list:
# Inicio: '/'
# Archivo: '/archive'